// Curated icon registry. Data files reference icons by string name; this maps
// them to explicitly-imported lucide-react components so the bundle stays lean.
import {
  Home,
  Users,
  Scale,
  Building2,
  Gavel,
  Shield,
  Receipt,
  BadgeIndianRupee,
  Stamp,
  Copyright,
  Landmark,
  FileText,
  ScrollText,
  UserCheck,
  Rocket,
  ShieldCheck,
  Clock,
  Lock,
  Languages,
  Headset,
  Search,
  Calendar,
  CalendarCheck,
  MessageSquare,
  CheckCircle2,
  Check,
  Star,
  Quote,
  Award,
  GraduationCap,
  TrendingUp,
  BookOpen,
  Heart,
  Sparkles,
  Filter,
  Briefcase,
  Phone,
  Mail,
  MapPin,
  Send,
  User,
  ThumbsUp,
  ArrowRight,
  ArrowUpRight,
  ChevronRight,
  ChevronDown,
} from "lucide-react";

const REGISTRY = {
  Home,
  Users,
  Scale,
  Building2,
  Gavel,
  Shield,
  Receipt,
  BadgeIndianRupee,
  Stamp,
  Copyright,
  Landmark,
  FileText,
  ScrollText,
  UserCheck,
  Rocket,
  ShieldCheck,
  Clock,
  Lock,
  Languages,
  Headset,
  Search,
  Calendar,
  CalendarCheck,
  MessageSquare,
  CheckCircle2,
  Check,
  Star,
  Quote,
  Award,
  GraduationCap,
  TrendingUp,
  BookOpen,
  Heart,
  Sparkles,
  Filter,
  Briefcase,
  Phone,
  Mail,
  MapPin,
  Send,
  User,
  ThumbsUp,
  ArrowRight,
  ArrowUpRight,
  ChevronRight,
  ChevronDown,
};

export default function Icon({ name, className, strokeWidth = 1.75, ...props }) {
  const Cmp = REGISTRY[name] || Sparkles;
  return <Cmp className={className} strokeWidth={strokeWidth} {...props} />;
}
